name: Test and Deploy

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npm run type-check

      - name: Build project
        run: npm run build

  api-integration-test:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Test API Endpoints
        run: npm run test:api
        env:
          NEXT_PUBLIC_STACK_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_STACK_PROJECT_ID }}
          NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY: ${{ secrets.NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY }}
          STACK_SECRET_SERVER_KEY: ${{ secrets.STACK_SECRET_SERVER_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BAWS_ACCESS_KEY_ID: ${{ secrets.BAWS_ACCESS_KEY_ID }}
          BAWS_SECRET_ACCESS_KEY: ${{ secrets.BAWS_SECRET_ACCESS_KEY }}
          DEFAULT_REGION: ${{ secrets.DEFAULT_REGION }}
          BEDROCK_REGION: ${{ secrets.BEDROCK_REGION }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          LLAMAINDEX_API_KEY: ${{ secrets.LLAMAINDEX_API_KEY }}

  deploy:
    runs-on: ubuntu-latest
    needs: [test, api-integration-test]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Amplify
        run: |
          echo "🚀 Deployment triggered automatically via Amplify webhook"
          echo "Monitor deployment status in AWS Amplify console"